package:
  name: regex
  version: 2026.9.3
  tag:
    - core
    - min-scipy-stack
  top-level:
    - regex
source:
  sha256: aabd43208e335f4c3f0b56de3464b066dd425983a58f6eeb5738bcd7465403db
  url: https://files.pythonhosted.org/packages/source/r/regex/regex-2026.9.3.tar.gz
about:
  home: https://github.com/mrabarnett/mrab-regex
  PyPI: https://pypi.org/project/regex
  summary: Alternative regular expression module, to replace re.
  license: Apache-2.0
