package:
  name: regex
  version: 2025.11.3
  tag:
    - core
    - min-scipy-stack
  top-level:
    - regex
source:
  sha256: 1fedc720f9bb2494ce31a58a1631f9c82df6a09b49c19517ea5cc280b4541e01
  url: https://files.pythonhosted.org/packages/source/r/regex/regex-2025.11.3.tar.gz
about:
  home: https://github.com/mrabarnett/mrab-regex
  PyPI: https://pypi.org/project/regex
  summary: Alternative regular expression module, to replace re.
  license: Apache-2.0
