package:
  name: pyproj
  version: 3.8.0
  top-level:
    - pyproj
source:
  url: https://files.pythonhosted.org/packages/source/p/pyproj/pyproj-3.8.0.tar.gz
  sha256: efa59725bba68bf97fa808b61302df32934acdceb6a5c92a8dd0e71dc266a876

requirements:
  host:
    - libproj

build:
  script: |
    export PROJ_VERSION=9.6.2
    export PROJ_DIR=${WASM_LIBRARY_DIR}
    export PROJ_INCDIR=${WASM_LIBRARY_DIR}/include
    export PROJ_LIBDIR=${WASM_LIBRARY_DIR}/lib
    export PROJ_WHEEL=1
    mkdir -p pyproj/proj_dir/share
    cp -r ${WASM_LIBRARY_DIR}/share/proj pyproj/proj_dir/share
  vendor-sharedlib: true
test:
  imports:
    - pyproj

about:
  home: https://github.com/pyproj4/pyproj
  PyPI: https://pypi.org/project/pyproj/
  summary:
    Python interface to PROJ (cartographic projections and coordinate transformations
    library)
  license: MIT