package:
  name: msgpack
  version: 1.2.1
  top-level:
    - msgpack
source:
  sha256: 04c721c2c7448767e9e3f2520a475663d8ee0f09c31890f6d2bd70fd636a9647
  url: https://files.pythonhosted.org/packages/source/m/msgpack/msgpack-1.2.1.tar.gz
about:
  home: https://msgpack.org/
  PyPI: https://pypi.org/project/msgpack
  summary: MessagePack serializer
  license: Apache-2.0
