package:
  name: pydantic_core
  version: 2.46.5
  tag:
    - rust
  # Warning: pydantic has a pin on pydantic_core, they need to be updated
  # together
  top-level:
    - pydantic_core
source:
  url: https://files.pythonhosted.org/packages/source/p/pydantic_core/pydantic_core-2.46.5.tar.gz
  sha256: 10416c15b8839ecc4ef4d0885da76da6fd0f67333a0eb8aff6d93c4b8f2910fc
requirements:
  executable:
    - rustup
about:
  home: https://github.com/pydantic/pydantic-core
  PyPI: https://pypi.org/project/pydantic_core
  summary: ""
  license: MIT
extra:
  recipe-maintainers:
    - samuelcolvin
