package:
  name: pyicon-diagnostics
  version: 0.4.0
  top-level:
    - pyicon
source:
  url: https://files.pythonhosted.org/packages/source/p/pyicon_diagnostics/pyicon_diagnostics-0.4.0.tar.gz
  sha256: 38606b846f9b14a65cb71fec2e95de0fe978da14604c976ffe815c995b348e02
  extras:
    - [./extras/requirements_development.txt, ./requirements_development.txt]
    - [./extras/requirements_documentation.txt, ./requirements_documentation.txt]
  patches:
    - patches/0001-no-jupyter-dependencies.patch

about:
  home: https://gitlab.dkrz.de/m300602/pyicon
  PyPI: https://pypi.org/project/pyicon-diagnostics
  summary: Diagnostic python software package for ICON
  license: MIT
