package:
  name: blosc2
  version: 3.12.2
  top-level:
    - blosc2
source:
  url: https://files.pythonhosted.org/packages/source/b/blosc2/blosc2-3.12.2.tar.gz
  sha256: a42f915c4b73e788bdc205c5473dcd8dd7a0290693408be471391d0ca65fe39f
build:
  backend-flags: |
    skbuild.cmake.define.WITH_OPTIM=OFF

requirements:
  host:
    - numpy

about:
  home: https://github.com/Blosc/python-blosc2
  PyPI: https://pypi.org/project/blosc2
  summary: A fast & compressed ndarray library with a flexible compute engine.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - FrancescAlted
