package:
  name: hdf5plugin
  version: 7.0.0
  top-level:
    - hdf5plugin
source:
  url: https://files.pythonhosted.org/packages/source/h/hdf5plugin/hdf5plugin-7.0.0.tar.gz
  sha256: e6e6b1f8b0c4d2ca87e616ddc31d08330b36207e466357040f95269e5e0401c8
  patches:
    - patches/0001-no-openmp.patch
    - patches/0002-sperr.patch
    - patches/0003-sz3.patch
    - patches/0004-hdf5-path.patch
    - patches/0005-link-hdf5.patch
    - patches/0006-zfp-word-type.patch
    - patches/0007-sz-fix-pointer-size.patch
requirements:
  host:
    - libhdf5
build:
  vendor-sharedlib: false
  exports: requested
about:
  home: https://github.com/silx-kit/hdf5plugin
  PyPI: https://pypi.org/project/hdf5plugin
  summary: HDF5 Plugins for Windows, MacOS, and Linux
  license: MIT
extra:
  recipe-maintainers:
    - juntyr
