package:
  name: hdf5plugin
  version: 6.0.0
  top-level:
    - hdf5plugin
source:
  url: https://files.pythonhosted.org/packages/source/h/hdf5plugin/hdf5plugin-6.0.0.tar.gz
  sha256: 847ed9e96b451367a110f0ba64a3b260d38d64bbf3f25751858d3b56e094cfe0
  patches:
    - patches/0001-no-openmp.patch
    - patches/0002-sperr.patch
    - patches/0003-sz3.patch
    - patches/0004-hdf5-path.patch
    - patches/0005-link-hdf5.patch
    - patches/0006-zfp-word-type.patch
requirements:
  host:
    - libhdf5
build:
  vendor-sharedlib: false
about:
  home: https://github.com/silx-kit/hdf5plugin
  PyPI: https://pypi.org/project/hdf5plugin
  summary: HDF5 Plugins for Windows, MacOS, and Linux
  license: MIT
extra:
  recipe-maintainers:
    - juntyr
