package:
  name: hdf5plugin
  version: 7.1.0
  top-level:
    - hdf5plugin
source:
  url: https://files.pythonhosted.org/packages/source/h/hdf5plugin/hdf5plugin-7.1.0.tar.gz
  sha256: dc4aa9576bf5770d773be9309a060ccf2f0ce2f0031f2b369f566d2662ec2fb3
  patches:
    - patches/0001-no-openmp.patch
    - patches/0002-sperr.patch
    - patches/0003-sz3.patch
    - patches/0004-hdf5-path.patch
    - patches/0005-link-hdf5.patch
    - patches/0006-zfp-word-type.patch
    - patches/0007-sz-fix-pointer-size.patch
requirements:
  host:
    - libhdf5
build:
  vendor-sharedlib: false
  exports: requested
about:
  home: https://github.com/silx-kit/hdf5plugin
  PyPI: https://pypi.org/project/hdf5plugin
  summary: HDF5 Plugins for Windows, MacOS, and Linux
  license: MIT
extra:
  recipe-maintainers:
    - juntyr
