package:
  name: torch
  version: 2.13.0
  top-level:
    - torch
source:
  url: https://gist.github.com/juntyr/c2fec79998f673c4d59dab07e8a9c308/raw/5ca2cf810852030f7a902f0471d0562da3c25234/torch-2.13.0-cp314-cp314-pyemscripten_2026_0_wasm32.whl
  sha256: 00301b5e327747e889a2b17d036af1b4c5f00947aba6cdc3f19c243429cc1260
about:
  home: https://pytorch.org/
  PyPI: https://pypi.org/project/torch
  summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
  license: Apache-2.0 AND Apache-2.0 WITH LLVM-exception AND BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND MIT
