package:
  name: torch
  version: 2.13.0
  top-level:
    - torch
source:
  url: https://github.com/mmtftr/pyodide-pytorch/releases/download/torch-2.13.0-pyodide-314.0.2-r6/torch-2.13.0+pyodide314.0.2.r6-cp314-cp314-pyemscripten_2026_0_wasm32.whl
  sha256: 4f7fb41b87ff870f86ee79f6ba089e0fe2ec618c61518fbe951146d5d074b86c
about:
  home: https://pytorch.org/
  PyPI: https://pypi.org/project/torch
  summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
  license: Apache-2.0 AND Apache-2.0 WITH LLVM-exception AND BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND MIT
