package:
  name: wrapt
  version: 2.1.1
  top-level:
    - wrapt
source:
  url: https://files.pythonhosted.org/packages/source/w/wrapt/wrapt-2.1.1.tar.gz
  sha256: 5fdcb09bf6db023d88f312bd0767594b414655d58090fc1c46b3414415f67fac
about:
  home: https://github.com/GrahamDumpleton/wrapt
  PyPI: https://pypi.org/project/wrapt
  summary: Module for decorators, wrappers and monkey patching.
  license: BSD-2-Clause
