package:
  name: wrapt
  version: 1.17.3
  top-level:
    - wrapt
source:
  url: https://files.pythonhosted.org/packages/source/w/wrapt/wrapt-1.17.3.tar.gz
  sha256: f66eb08feaa410fe4eebd17f2a2c8e2e46d3476e9f8c783daa8e09e0faa666d0
about:
  home: https://github.com/GrahamDumpleton/wrapt
  PyPI: https://pypi.org/project/wrapt
  summary: Module for decorators, wrappers and monkey patching.
  license: BSD-2-Clause
