package:
  name: aiohttp
  version: 3.14.1
  top-level:
    - aiohttp
source:
  url: https://files.pythonhosted.org/packages/source/a/aiohttp/aiohttp-3.14.1.tar.gz
  sha256: 307f2cff90a764d329e77040603fa032db89c5c24fdad50c4c15334cba744035
  patches:
    - patches/0001-pyodide-connection.patch
    - patches/0002-export-http-exceptions.patch
    - patches/0003-requires-jupyterlite-cors.patch

about:
  home: https://github.com/aio-libs/aiohttp
  PyPI: https://pypi.org/project/aiohttp
  summary: Async http client/server framework (asyncio)
  license: Apache-2.0
