package:
  name: aiohttp
  version: 3.13.3
  top-level:
    - aiohttp
source:
  url: https://files.pythonhosted.org/packages/source/a/aiohttp/aiohttp-3.13.3.tar.gz
  sha256: a949eee43d3782f2daae4f4a2819b2cb9b0c5d3b7f7a927067cc84dafdbb9f88
  patches:
    - patches/0001-pyodide-connection.patch
    - patches/0002-export-http-exceptions.patch
    - patches/0003-requires-jupyterlite-cors.patch

about:
  home: https://github.com/aio-libs/aiohttp
  PyPI: https://pypi.org/project/aiohttp
  summary: Async http client/server framework (asyncio)
  license: Apache-2.0
