package:
  name: crc32c
  version: "2.9"
  top-level:
    - crc32c
source:
  url: https://files.pythonhosted.org/packages/source/c/crc32c/crc32c-2.9.tar.gz
  sha256: d6d2ae0299a417e5fb2e3641838cec34a23778a62fb4ce928792366476c1983b
about:
  home: https://github.com/ICRAR/crc32c
  PyPI: https://pypi.org/project/crc32c
  summary: A python package implementing the crc32c algorithm in hardware and
    software
  license: LGPL-2.1+
extra:
  recipe-maintainers:
    - agriyakhetarpal
