package:
  name: orjson
  version: 3.11.9
  tag:
    - rust
  top-level:
    - orjson
source:
  url: https://files.pythonhosted.org/packages/source/o/orjson/orjson-3.11.9.tar.gz
  sha256: 4fef17e1f8722c11587a6ef18e35902450221da0028e65dbaaa543619e68e48f
build:
  script: |
    export RUSTUP_TOOLCHAIN="1.95"
    rustup target add wasm32-unknown-emscripten --toolchain ${RUSTUP_TOOLCHAIN}
requirements:
  executable:
    - rustup
about:
  home: https://github.com/ijl/orjson
  PyPI: https://pypi.org/project/orjson
  summary: Fast, correct Python JSON library supporting dataclasses, datetimes,
    and numpy
  license: Apache-2.0 OR MIT
extra:
  recipe-maintainers:
    - spicy-sauce
