package:
  name: orjson
  version: 3.12.0
  tag:
    - rust
  top-level:
    - orjson
source:
  url: https://files.pythonhosted.org/packages/source/o/orjson/orjson-3.12.0.tar.gz
  sha256: d14203fb1aae2ad9b3d52f8a0e82aeb10197ef1c9bc61da7f358bd70b00123d5
build:
  script: |
    export RUSTUP_TOOLCHAIN="1.95"
    rustup target add wasm32-unknown-emscripten --toolchain ${RUSTUP_TOOLCHAIN}
requirements:
  executable:
    - rustup
about:
  home: https://github.com/ijl/orjson
  PyPI: https://pypi.org/project/orjson
  summary: Fast, correct Python JSON library supporting dataclasses, datetimes,
    and numpy
  license: Apache-2.0 OR MIT
extra:
  recipe-maintainers:
    - spicy-sauce
