package:
  name: polars
  version: 1.32.3
  top-level:
    - polars
source:
  url: https://github.com/juntyr/polars-pyodide/releases/download/polars-1.32.3-pyodide-0.29.3/polars-1.32.3-cp313-cp313-pyodide_2025_0_wasm32.whl
  sha256: 171908b44136f5083560452ddbdc10a20e96e25e67f031d0d5c8e75004f22d2e
about:
  home: https://github.com/pola-rs/polars
  PyPI: https://pypi.org/project/polars
  summary: Blazingly fast DataFrame library
  license: MIT
