package:
  name: eccodes
  version: 2.45.0
  top-level:
    - eccodes
    - gribapi
source:
  url: https://github.com/ecmwf/eccodes-python/archive/refs/tags/2.45.0.tar.gz
  sha256: 05f1ee6d9647fbd7fc1f601027ab129e0ccf749b6069e2e47a7365ff63bb6860
  patches:
    - patches/0001-package-shared-library.patch
    - patches/0002-library-path.patch
    - patches/0003-no-circular-import.patch
requirements:
  host:
    - libeccodes
build:
  vendor-sharedlib: true
about:
  home: https://github.com/ecmwf/eccodes-python
  PyPI: https://pypi.org/project/eccodes
  summary: Python interface to the ecCodes GRIB and BUFR decoder/encoder
  license: Apache License Version 2.0
