package:
  name: eccodes
  version: 2.42.0
  top-level:
    - eccodes
    - gribapi
source:
  url: https://github.com/ecmwf/eccodes-python/archive/refs/tags/2.42.0.tar.gz
  sha256: 0c157e4c96ea3f7b7ece7749af28e4ed0e2e4fd2a7f8ee909e6f77c19653d9d1
  patches:
    - patches/0001-package-shared-library.patch
requirements:
  host:
    - libeccodes
build:
  vendor-sharedlib: true
about:
  home: https://github.com/ecmwf/eccodes-python
  PyPI: https://pypi.org/project/eccodes
  summary: Python interface to the ecCodes GRIB and BUFR decoder/encoder
  license: Apache License Version 2.0
