package:
  name: eccodes
  version: 2.47.0
  top-level:
    - eccodes
    - gribapi
source:
  url: https://github.com/ecmwf/eccodes-python/archive/refs/tags/2.47.0.tar.gz
  sha256: 5a4336321349342110e8766ee52280f2a97ef64cd95eb013166cb8d75c69cfd8
  patches:
    - patches/0001-package-shared-library.patch
    - patches/0002-library-path.patch
    - patches/0003-no-circular-import.patch
requirements:
  host:
    - libeccodes
build:
  vendor-sharedlib: true
about:
  home: https://github.com/ecmwf/eccodes-python
  PyPI: https://pypi.org/project/eccodes
  summary: Python interface to the ecCodes GRIB and BUFR decoder/encoder
  license: Apache License Version 2.0
