package:
  name: pyrosm
  version: 0.13.1
  top-level:
    - pyrosm
source:
  url: https://files.pythonhosted.org/packages/source/p/pyrosm/pyrosm-0.13.1.tar.gz
  sha256: 984692c106153adbb6eacf5f698849ee6bbc8eeff6c74a3c76f2204be8a881ef
about:
  home: https://pyrosm.readthedocs.io/
  PyPI: https://pypi.org/project/pyrosm
  summary: A Python tool to parse OSM data from Protobuf format into GeoDataFrame.
  license: MIT
extra:
  recipe-maintainers:
    - juntyr
