package:
  name: pyrosm
  version: 0.6.2
  top-level:
    - pyrosm
source:
  url: https://files.pythonhosted.org/packages/source/p/pyrosm/pyrosm-0.6.2.tar.gz
  sha256: 904e9636e71fd558d127807a0beb9b53e4d2e28a2301d3c46ed8ba2d84d5e1b9
  patches:
    - patches/0001-install-no-build-dependencies.patch
about:
  home: https://pyrosm.readthedocs.io/
  PyPI: https://pypi.org/project/pyrosm
  summary: A Python tool to parse OSM data from Protobuf format into
    GeoDataFrame.
  license: MIT
extra:
  recipe-maintainers:
    - juntyr
