package:
  name: rpds-py
  version: 2026.6.3
  tag:
    - rust
  top-level:
    - rpds
source:
  url: https://files.pythonhosted.org/packages/source/r/rpds_py/rpds_py-2026.6.3.tar.gz
  sha256: 1cebd1337c242e4ec2293e541f712b2da849b29f48f0c293684b71c0632625d4
requirements:
  executable:
    - rustup
about:
  home: https://rpds.readthedocs.io
  PyPI: https://pypi.org/project/rpds-py
  summary: Python bindings to Rust's persistent data structures (rpds)
  license: MIT
