package:
  name: kiwisolver
  version: 1.4.9
  top-level:
    - kiwisolver
source:
  sha256: c3b22c26c6fd6811b0ae8363b95ca8ce4ea3c202d3d0975b2914310ceb1bcc4d
  url: https://files.pythonhosted.org/packages/source/k/kiwisolver/kiwisolver-1.4.9.tar.gz
about:
  home: https://github.com/nucleic/kiwi
  license: BSD-3-Clause
