package:
  name: fsspec
  version: 2025.12.0
  top-level:
    - fsspec
source:
  url: https://files.pythonhosted.org/packages/source/f/fsspec/fsspec-2025.12.0.tar.gz
  sha256: c505de011584597b1060ff778bb664c1bc022e87921b0e4f10cc9c44f9635973
  patches:
    - patches/0001-syncify-awaitable.patch
about:
  home: http://github.com/fsspec/filesystem_spec
  PyPI: https://pypi.org/project/fsspec
  summary: File-system specification
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - joemarshall
