package:
  name: fsspec
  version: 2026.7.0
  top-level:
    - fsspec
source:
  url: https://files.pythonhosted.org/packages/source/f/fsspec/fsspec-2026.7.0.tar.gz
  sha256: c803c40f4cf860b49dea58ee3e1c33cb9c790520e233537e1340049f89b82a88
  patches:
    - patches/0001-syncify-awaitable.patch
about:
  home: http://github.com/fsspec/filesystem_spec
  PyPI: https://pypi.org/project/fsspec
  summary: File-system specification
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - joemarshall
