package:
  name: fsspec
  version: 2026.2.0
  top-level:
    - fsspec
source:
  url: https://files.pythonhosted.org/packages/source/f/fsspec/fsspec-2026.2.0.tar.gz
  sha256: 6544e34b16869f5aacd5b90bdf1a71acb37792ea3ddf6125ee69a22a53fb8bff
  patches:
    - patches/0001-syncify-awaitable.patch
about:
  home: http://github.com/fsspec/filesystem_spec
  PyPI: https://pypi.org/project/fsspec
  summary: File-system specification
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - joemarshall
