package:
  name: ujson
  version: 5.13.0
  top-level:
    - ujson
source:
  url: https://files.pythonhosted.org/packages/source/u/ujson/ujson-5.13.0.tar.gz
  sha256: d62e3d7625384c08082abad81a077af587fdef2761bb14c3822f4234b8d07d75
about:
  home: https://github.com/ultrajson/ultrajson
  PyPI: https://pypi.org/project/ujson
  summary: Ultra fast JSON encoder and decoder for Python
  license: BSD-2-Clause
extra:
  recipe-maintainers:
    - greateggsgreg
