package:
  name: healpy
  version: 1.20.0
  top-level:
    - healpy
source:
  url: https://files.pythonhosted.org/packages/source/h/healpy/healpy-1.20.0.tar.gz
  sha256: 03b0e1551ae235c7290e9bfdf69fa9cdc194f8a2be51198c1924b15d826102ed
  patches:
    - patches/0001-Skip-linking-cfitsio-and-healpix_cxx-programs-for-Py.patch
    - patches/0002-without-zlib-check-fortran.patch
    - patches/0003-install-path.patch
    - patches/0004-disable-openmp.patch
requirements:
  host:
    - libzlib
    - numpy
build:
  vendor-sharedlib: true
  exports: requested
  cflags: |
    -I$(WASM_LIBRARY_DIR)/include
    -fwasm-exceptions
  cxxflags: |
    -fwasm-exceptions
  ldflags: |
    -fwasm-exceptions
  script: |
    export CXXFLAGS="$CXXFLAGS -sSIDE_MODULE=1"

    # ensure that dependencies are rebuilt
    rm -f ${WASM_LIBRARY_DIR}/lib/pkgconfig/cfitsio.pc
    rm -f ${WASM_LIBRARY_DIR}/lib/pkgconfig/healpix_cxx.pc
    rm -f ${WASM_LIBRARY_DIR}/lib/pkgconfig/libsharp.pc
about:
  home: https://github.com/healpy/healpy
  PyPI: https://pypi.org/project/healpy
  summary: Healpix tools package for Python
  license: GPL-2.0-only
extra:
  recipe-maintainers:
    - juntyr
