package:
  name: zarr
  version: 3.1.5
  top-level:
    - zarr
source:
  sha256: fbe0c79675a40c996de7ca08e80a1c0a20537bd4a9f43418b6d101395c0bba2b
  url: https://files.pythonhosted.org/packages/source/z/zarr/zarr-3.1.5.tar.gz
  patches:
    - patches/0001-syncify-awaitable.patch
about:
  home: https://github.com/zarr-developers/zarr-python
  PyPI: https://pypi.org/project/zarr
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python.
  license: MIT
