package:
  name: zarr
  version: 3.3.0
  top-level:
    - zarr
source:
  sha256: cd0c8cf738b4bb4807815bc1255acad5bdf1a7b7264b606c5a1bc0d0392a306b
  url: https://files.pythonhosted.org/packages/source/z/zarr/zarr-3.3.0.tar.gz
  patches:
    - patches/0001-Add-WASM-compatible-sync-for-Pyodide.patch
    - patches/0002-Set-threading.max_workers-1-on-WASM-in-config.patch
    - patches/0003-Fix-exclusive-atomic-writes-on-Emscripten.patch
about:
  home: https://github.com/zarr-developers/zarr-python
  PyPI: https://pypi.org/project/zarr
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python
  license: MIT
