package:
  name: zarr
  version: 3.0.8
  top-level:
    - zarr
source:
  sha256: 88505d095af899a88ae8ac4db02f4650ef0801d2ff6f65b6d1f0a45dcf760a6d
  url: https://files.pythonhosted.org/packages/source/z/zarr/zarr-3.0.8.tar.gz
  patches:
    - patches/0001-syncify-awaitable.patch
about:
  home: https://github.com/zarr-developers/zarr-python
  PyPI: https://pypi.org/project/zarr
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python.
  license: MIT
