package:
  name: numba
  version: 0.63.1
  top-level:
    - numba
source:
  path: ./numba
about:
  home: https://numba.pydata.org
  PyPI: https://pypi.org/project/numba
  summary: compiling Python code using LLVM, minimally mocked for Pyodide
  license: BSD
