package:
  name: pyzmq
  version: 27.2.0
  top-level:
    - zmq
source:
  url: https://files.pythonhosted.org/packages/source/p/pyzmq/pyzmq-27.2.0.tar.gz
  sha256: 54d4259d1bfae24ecdb5ca79f7acc2eac6c286a02d6a0ae617797cb45f0726d3
about:
  home: https://github.com/zeromq/pyzmq
  PyPI: https://pypi.org/project/pyzmq
  summary: Python bindings for 0MQ
  license: BSD 3-Clause
