package:
  name: scikit-image
  version: 0.26.0
  top-level:
    - skimage
      # - doc  # scikit-image has top level `doc` directory... but it is too common name so we don't want to use it as a hint for top-level import.
source:
  sha256: f5f970ab04efad85c24714321fcc91613fcb64ef2a892a13167df2f3e59199fa
  url: https://files.pythonhosted.org/packages/source/s/scikit_image/scikit_image-0.26.0.tar.gz

build:
  script: |
    export CFLAGS=${SIDE_MODULE_CFLAGS}
    export LDFLAGS=${SIDE_MODULE_LDFLAGS}

requirements:
  host:
    - numpy

about:
  home: https://scikit-image.org
  PyPI: https://pypi.org/project/scikit-image
  summary: Image processing in Python
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - lagru
    - mkcor
