package:
  name: netCDF4
  version: 1.7.3
  top-level:
    - netCDF4
source:
  url: https://files.pythonhosted.org/packages/source/n/netcdf4/netcdf4-1.7.3.tar.gz
  sha256: 83f122fc3415e92b1d4904fd6a0898468b5404c09432c34beb6b16c533884673
requirements:
  host:
    - libhdf5
    - libnetcdf
test:
  imports:
    - netCDF4
build:
  vendor-sharedlib: true
  script: |
    export PATH=${WASM_LIBRARY_DIR}/bin:${PATH}
    export HDF5_DIR=${WASM_LIBRARY_DIR}
    echo ${HDF5_DIR}
  ldflags: |
    -L$(WASM_LIBRARY_DIR)/lib
    -lhdf5
    -lhdf5_hl
about:
  home: https://github.com/Unidata/netcdf4-python
  PyPI: https://pypi.org/project/netcdf4
  summary: Provides an object-oriented python interface to the netCDF version 4
    library
  license: MIT
