package:
  name: rasterio
  version: 1.5.1
  top-level:
    - rasterio
source:
  url: https://files.pythonhosted.org/packages/source/r/rasterio/rasterio-1.5.1.tar.gz
  sha256: c1b6ae15f4ccad704f1fe8417da5c2250145c7bcdb91acb53833bf5aefdd9e48
requirements:
  host:
    - numpy
    - libgdal
    - libproj
build:
  vendor-sharedlib: true
  script: |
    export PACKAGE_DATA=1
    export GDAL_CONFIG=${WASM_LIBRARY_DIR}/bin/gdal-config
    export GDAL_DATA=${WASM_LIBRARY_DIR}/share/gdal
    export PROJ_LIB=${WASM_LIBRARY_DIR}/share/proj
    echo ${GDAL_CONFIG}
    echo ${GDAL_DATA}
    echo ${PROJ_LIB}
test:
  imports:
    - rasterio
about:
  home: https://github.com/rasterio/rasterio
  PyPI: https://pypi.org/project/rasterio
  summary: Fast and direct raster I/O for use with Numpy and SciPy
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - kjmalek
