package:
  name: cf-python
  version: 3.18.2
  top-level:
    - cf
source:
  url: https://files.pythonhosted.org/packages/source/c/cf_python/cf_python-3.18.2.tar.gz
  sha256: fa80b9499d433902bd2d093700ef2c76ab6541f501a393b2135f0c032d824e45
  patches:
    - patches/0001-make-clean.patch
    - patches/0002-no-psutil-distributed.patch
about:
  home: https://ncas-cms.github.io/cf-python
  PyPI: https://pypi.org/project/cf-python
  summary: A CF-compliant earth science data analysis library
  license: MIT
