package:
  name: cf-python
  version: 3.20.1
  top-level:
    - cf
source:
  url: https://files.pythonhosted.org/packages/source/c/cf_python/cf_python-3.20.1.tar.gz
  sha256: 0c7ea20e86fd65a2f470d34da703e72af021c411a746f3fd838a1713e8b49fae
  patches:
    - patches/0001-make-clean.patch
    - patches/0002-no-psutil-distributed.patch
about:
  home: https://ncas-cms.github.io/cf-python
  PyPI: https://pypi.org/project/cf-python
  summary: A CF-compliant earth science data analysis library
  license: MIT
