package:
  name: cffi
  version: 1.17.1
  top-level:
    - cffi
source:
  url: https://files.pythonhosted.org/packages/source/c/cffi/cffi-1.17.1.tar.gz
  sha256: 1c39c6016c32bc48dd54561950ebd6836e1670f2ae46128f67cf49e789c52824
build:
  cross-build-env: true
about:
  home: http://cffi.readthedocs.org
  PyPI: https://pypi.org/project/cffi
  summary: Foreign Function Interface for Python calling C code.
  license: MIT
