package:
  name: pyogrio
  version: 0.13.0
  top-level:
    - pyogrio
source:
  url: https://files.pythonhosted.org/packages/source/p/pyogrio/pyogrio-0.13.0.tar.gz
  sha256: 9614f27a1891113f80653e0b76b4233ea1fb3beeb1ac46d118ab22e1670f8f13
requirements:
  host:
    - libgdal
build:
  vendor-sharedlib: true
  script: |
    export PYOGRIO_PACKAGE_DATA=1

    export GDAL_CONFIG=${WASM_LIBRARY_DIR}/bin/gdal-config
    export GDAL_DATA=${WASM_LIBRARY_DIR}/share/gdal
    export PROJ_LIB=${WASM_LIBRARY_DIR}/share/proj
    echo ${GDAL_CONFIG} ${GDAL_DATA} ${PROJ_LIB}
about:
  home: https://github.com/geopandas/pyogrio
  PyPI: https://pypi.org/project/pyogrio
  summary: Vectorized spatial vector file format I/O using GDAL/OGR
  license: MIT License
