package:
  name: cfdm
  version: 1.13.2.1
  top-level:
    - cfdm
source:
  url: https://files.pythonhosted.org/packages/source/c/cfdm/cfdm-1.13.2.1.tar.gz
  sha256: e937bfde036e235af60c8dd8c4143185730b67855d21ceca040b7e2df0188eac
  patches:
    - patches/0001-no-distributed.patch
    - patches/0002-udunits-library-path.patch
about:
  home: https://ncas-cms.github.io/cfdm
  PyPI: https://pypi.org/project/cfdm
  summary: A Python reference implementation of the CF data model
  license: MIT
