package:
  name: libatlas
  version: 0.46.0

source:
  url: https://github.com/ecmwf/atlas/archive/refs/tags/0.46.0.tar.gz
  sha256: 482d92e0dd0c2cffe5af9aeffd9681f64e21f3dbf2b34d51fa3aa805de0a7370
  patches:
    - patches/0001-disable-tests.patch
    - patches/0002-no-floating-point-exceptions.patch
    - patches/0003-fix-iterator.patch

requirements:
  host:
    - libeckit

build:
  type: shared_library
  script: |
    git clone --branch 3.7.0 --depth 1 https://github.com/ecmwf/ecbuild;

    mkdir -p build;

    export CFLAGS="${CFLAGS} -fwasm-exceptions -sSUPPORT_LONGJMP='wasm'"
    export CXXFLAGS="${CXXFLAGS} -fwasm-exceptions -sSUPPORT_LONGJMP='wasm'"
    export LDFLAGS="${LDFLAGS} -fwasm-exceptions -sSUPPORT_LONGJMP='wasm'"

    export EMSCRIPTEN_SYSROOT=$(em-config CACHE)/sysroot
    export EMSCRIPTEN_INCLUDE=$EMSCRIPTEN_SYSROOT/include
    export EMSCRIPTEN_BIN=$EMSCRIPTEN_SYSROOT/bin
    export EMSCRIPTEN_LIB=$EMSCRIPTEN_SYSROOT/lib/wasm32-emscripten/pic

    cd build \
        && emcmake cmake ../ \
        -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
        -DBUILD_SHARED_LIBS=ON \
        -DDISABLE_OS_CHECK=ON \
        -DENABLE_TESTS=OFF \
        -DENABLE_FORTRAN=OFF \
        -DCMAKE_C_FLAGS="-fwasm-exceptions" \
        -DCMAKE_CXX_FLAGS="-fwasm-exceptions";

    emmake make -j ${PYODIDE_JOBS:-3};
    emmake make -j ${PYODIDE_JOBS:-3} install;

    cp -P ${WASM_LIBRARY_DIR}/lib/libatlas.so ${DISTDIR}
