package:
  name: protobuf
  version: 7.36.1
  top-level:
  - google

source:
  url: 
    https://files.pythonhosted.org/packages/source/p/protobuf/protobuf-7.36.1.tar.gz
  sha256: d0f6470f0ce2b84e3feaea2d4b816378b37ba4d4aa08a274305373de93e2d524

about:
  home: https://github.com/protocolbuffers/protobuf
  PyPI: https://pypi.org/project/protobuf
  summary: Protocol Buffers are a language-neutral, platform-neutral extensible 
    mechanism for serializing structured data
  license: BSD-3-Clause

build:
  cflags: -Wno-int-conversion

extra:
  recipe-maintainers:
  - bartbroere
