package:
  name: protobuf
  version: 7.35.1
  top-level:
  - google

source:
  url: 
    https://files.pythonhosted.org/packages/source/p/protobuf/protobuf-7.35.1.tar.gz
  sha256: ce115a26fe0c39a2c29973d914d327e516a6455464489fe3cd1e51a1b354f81a

about:
  home: https://github.com/protocolbuffers/protobuf
  PyPI: https://pypi.org/project/protobuf
  summary: Protocol Buffers are a language-neutral, platform-neutral extensible 
    mechanism for serializing structured data
  license: BSD-3-Clause

build:
  cflags: -Wno-int-conversion

extra:
  recipe-maintainers:
  - bartbroere
