package:
  name: arro3-io
  version: 0.8.0
  tag:
    - rust
  top-level:
    - "arro3.io"
source:
  url: https://github.com/kylebarron/arro3/archive/refs/tags/py-v0.8.0.tar.gz
  sha256: 7cbbe78b83aa70e76f7b4e8e456da64114ff4bab9fe72b16ddf505ea2fe2672a
  patches:
    - patches/0001-inline-workspace.patch
    - patches/0002-no-async.patch
    - patches/0003-fix-async-feature.patch
    - patches/0004-no-py-store.patch
requirements:
  executable:
    - rustup
build:
  script: |
    mv arro3-io .arro3-io
    rm -rf *
    rm -rf .github .gitignore .pre-commit-config.yaml .python-version
    mv .arro3-io/* .
    rm -rf .arro3-io
about:
  home: https://github.com/kylebarron/arro3
  PyPI: https://pypi.org/project/arro3-io
  summary: Read and write tabular data formats to and from Apache Arrow.
  license: MIT
extra:
  recipe-maintainers:
    - kylebarron
