package:
  name: libeccodes
  version: 2.44.0

source:
  url: https://github.com/ecmwf/eccodes/archive/refs/tags/2.44.0.tar.gz
  sha256: 9d5b01a20047eb7af2531a0aeccd60e32056d9d12790a8365844de376e631e8a
  patches:
    - patches/0001-32bit-support-hack.patch

requirements:
  host:
    - libaec

build:
  type: shared_library
  script: |
    git clone --branch 3.7.0 --depth 1 https://github.com/ecmwf/ecbuild;

    mkdir -p build;

    export CFLAGS="${CFLAGS} -fwasm-exceptions -sSUPPORT_LONGJMP='wasm'"
    export CXXFLAGS="${CXXFLAGS} -fwasm-exceptions -sSUPPORT_LONGJMP='wasm'"
    export LDFLAGS="${LDFLAGS} -fwasm-exceptions -sSUPPORT_LONGJMP='wasm'"

    export EMSCRIPTEN_SYSROOT=$(em-config CACHE)/sysroot
    export EMSCRIPTEN_INCLUDE=$EMSCRIPTEN_SYSROOT/include
    export EMSCRIPTEN_BIN=$EMSCRIPTEN_SYSROOT/bin
    export EMSCRIPTEN_LIB=$EMSCRIPTEN_SYSROOT/lib/wasm32-emscripten/pic

    embuilder build libjpeg --pic
    embuilder build libpng-legacysjlj --pic

    cd build \
        && emcmake cmake ../ \
        -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
        -DBUILD_SHARED_LIBS=ON \
        -DENABLE_NETCDF=OFF \
        -DENABLE_JPG=ON \
        -DENABLE_JPG_LIBOPENJPEG=OFF \
        -DENABLE_JPG_LIBJASPER=OFF \
        -DENABLE_PNG=ON \
        -DPNG_PNG_INCLUDE_DIR=$EMSCRIPTEN_INCLUDE \
        -DPNG_LIBRARY_RELEASE=$EMSCRIPTEN_LIB/libpng-legacysjlj.a \
        -DENABLE_AEC=ON \
        -DENABLE_FORTRAN=OFF \
        -DENABLE_MEMFS=ON \
        -DDISABLE_OS_CHECK=ON \
        -DENABLE_TESTS=OFF \
        -DENABLE_PRODUCT_GRIB=ON \
        -DENABLE_PRODUCT_BUFR=ON \
        -DENABLE_EXAMPLES=OFF \
        -DENABLE_BUILD_TOOLS=OFF \
        -DENABLE_INSTALL_ECCODES_DEFINITIONS=ON \
        -DENABLE_INSTALL_ECCODES_SAMPLES=OFF \
        -DCMAKE_C_FLAGS="-fwasm-exceptions" \
        -DCMAKE_CXX_FLAGS="-fwasm-exceptions";

    emmake make -j ${PYODIDE_JOBS:-3};
    emmake make -j ${PYODIDE_JOBS:-3} install;

    cp -P ${WASM_LIBRARY_DIR}/lib/libeccodes.so ${DISTDIR}
